# -*- coding: utf-8 -*-
"""Backend Code Reference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X79JawAe2VhGQlJuvC9M4Q2vIhg6LjB7
"""

from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel, Field
from typing import List, Optional
import datetime
import json
# 假设内部部署了本地大模型 (如 Llama-3) 或调用脱敏后的商业 API
# import openai

app = FastAPI(title="AI-BD Tracker API", version="1.0.0")

# --- 1. 数据模型 (Pydantic Models) ---
class TaskSchema(BaseModel):
    type: str = Field(description="meeting | share | follow_up")
    desc: str
    date: str
    status: str

class ProjectCreate(BaseModel):
    company: str
    pipeline: str
    stage: str = "Initial Contact"
    nextFollowUp: str
    tasks: List[TaskSchema] = []

class ProjectResponse(ProjectCreate):
    id: str
    lastContactDate: str
    status: str
    owner_name: str

class AIParsingRequest(BaseModel):
    raw_text: str

# 模拟的内存数据库 (生产环境应替换为 SQLAlchemy + PostgreSQL)
fake_db = {}

# --- 2. 核心接口：AI 解析非结构化沟通记录 ---
@app.post("/api/v1/extract", response_model=ProjectCreate)
async def ai_extract_bd_data(request: AIParsingRequest):
    """
    接收长文本（微信/邮件/纪要），调用大模型提取结构化数据
    """
    raw_text = request.raw_text

    # 真实的生产环境代码示例（伪代码）：
    # prompt = f"作为医药BD，提取以下文本中的公司、管线、阶段、跟进事项：\n{raw_text}"
    # response = openai.ChatCompletion.create(model="gpt-4", messages=[...])
    # parsed_data = json.loads(response.choices[0].message.content)

    # 这里模拟大模型返回的结果
    parsed_data = {
        "company": "Extracted Pharma Ltd.",
        "pipeline": "ADC Platform",
        "stage": "CDA Signed",
        "nextFollowUp": (datetime.datetime.now() + datetime.timedelta(days=7)).strftime('%Y-%m-%d'),
        "tasks": [
            {"type": "share", "desc": "Send updated non-confidential deck", "date": "Tomorrow", "status": "pending"}
        ]
    }
    return parsed_data

# --- 3. CRUD 接口：项目管理 ---
@app.post("/api/v1/projects", response_model=ProjectResponse)
async def create_project(project: ProjectCreate):
    """保存 AI 提取后确认的项目，或手动新建项目"""
    project_id = f"proj_{len(fake_db) + 1}"
    new_project = project.dict()
    new_project.update({
        "id": project_id,
        "lastContactDate": datetime.datetime.now().strftime('%Y-%m-%d'),
        "status": "active",
        "owner_name": "Alex Sterling" # 实际应从 Auth Token 获取
    })
    fake_db[project_id] = new_project
    return new_project

@app.get("/api/v1/projects", response_model=List[ProjectResponse])
async def list_projects():
    """获取所有项目，供 Dashboard 和 Kanban 使用"""
    return list(fake_db.values())

@app.patch("/api/v1/projects/{project_id}")
async def update_project_stage(project_id: str, new_stage: str):
    """看板拖拽：更新项目所处阶段"""
    if project_id not in fake_db:
        raise HTTPException(status_code=404, detail="Project not found")

    fake_db[project_id]["stage"] = new_stage
    return {"message": "Success", "project": fake_db[project_id]}

# 启动命令: uvicorn backend:app --reload